# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HKxjvGX2YpeFOH7YVIHhGWZq-0nMYDq
"""

import os, glob, random
import numpy as np
import torch
from torch.utils.data import Dataset
import cv2
import albumentations as A

def hu_window(img, level=40, width=80):
    lo = level - width/2
    hi = level + width/2
    img = np.clip(img, lo, hi)
    img = (img - lo) / (hi - lo)
    return img.astype(np.float32)

class SliceDataset(Dataset):
    """
    expects a directory with:
    images: .png or .npy  shape HxW or 1xHxW
    masks:  .png or .npy  binary masks HxW
    labels: csv or mapping for 6 class one hot [normal, IPH, IVH, SDH, SAH, EPH] example
    For simplicity we pass a list of tuples built offline.
    """
    def __init__(self, items, aug=True):
        self.items = items
        self.aug = aug
        self.tf = A.Compose([
            A.HorizontalFlip(p=0.5),
            A.Rotate(limit=15, p=0.5),
            A.RandomBrightnessContrast(p=0.25),
        ])

    def __len__(self):
        return len(self.items)

    def __getitem__(self, i):
        img_path, mask_path, cls_vec = self.items[i]
        if img_path.endswith(".npy"):
            img = np.load(img_path).astype(np.float32)
        else:
            img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED).astype(np.float32)
        if mask_path.endswith(".npy"):
            mask = np.load(mask_path).astype(np.float32)
        else:
            m = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
            mask = (m>127).astype(np.float32)

        # if this is HU space, window
        if img.max() > 2.0:
            img = hu_window(img, 40, 80)

        if img.ndim == 2:
            img = img[None, ...]
        if mask.ndim == 2:
            mask = mask[None, ...]

        img_np = img.transpose(1,2,0)  # H W C
        mask_np = mask.transpose(1,2,0)

        if self.aug:
            out = self.tf(image=(img_np*255).astype(np.uint8), mask=(mask_np*255).astype(np.uint8))
            img_np = out["image"].astype(np.float32)/255.0
            mask_np = (out["mask"].astype(np.float32)/255.0)

        img = torch.from_numpy(img_np.transpose(2,0,1))
        mask = torch.from_numpy(mask_np.transpose(2,0,1))
        cls = torch.tensor(cls_vec, dtype=torch.float32)
        return img, mask, cls