# -*- coding: utf-8 -*-
"""infer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HKxjvGX2YpeFOH7YVIHhGWZq-0nMYDq
"""

import argparse, json, os
import torch, cv2, numpy as np
from models.mtunet import MTUNet

def load_image(path):
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED).astype(np.float32)
    if img.max() > 2.0:
        # window to brain window
        lo, hi = 0.0, 80.0
        img = np.clip(img-40.0, lo, hi) / hi
    if img.ndim == 2:
        img = img[None, ...]
    return img

@torch.no_grad()
def main(args):
    ckpt = torch.load(args.ckpt, map_location="cpu")
    model = MTUNet(in_ch=1, num_classes=6, seg_classes=1, encoder_name=ckpt.get("encoder","tf_efficientnetv2_s"))
    model.load_state_dict(ckpt["model"])
    model.eval()

    img = load_image(args.image)
    x = torch.from_numpy(img[None, ...])
    logits_cls, logits_seg = model(x)
    prob_mask = torch.sigmoid(logits_seg)[0,0].numpy()
    mask = (prob_mask > args.thr).astype(np.uint8)*255
    out_path = os.path.join(args.out_dir, "pred_mask.png")
    os.makedirs(args.out_dir, exist_ok=True)
    cv2.imwrite(out_path, mask)
    print("saved", out_path)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--image", required=True)
    ap.add_argument("--out_dir", default="preds")
    ap.add_argument("--thr", type=float, default=0.5)
    args = ap.parse_args()
    main(args)

pip install <library_name>

"""Replace `<library_name>` with the actual name of the library you want to install. For example, to install `numpy`, you would use:

```python
pip install numpy
```
"""